version: "3.7"
services:
    gunicorn:
        image: codefroghq/codefrog:latest
        command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "8", "wsgi:application"]
        restart: unless-stopped
        build:
            context: .
            args:
                # Django
                - DEBUG
                - SECRET_KEY
                - ALLOWED_HOSTS
                - STATIC_ROOT
                - LOG_LEVEL
                # Database
                - DATABASE_URL
                # Celery
                - CELERY_BROKER_URL
                - CELERY_TASK_ALWAYS_EAGER
                - CELERY_WORKER_MAX_TASKS_PER_CHILD
                - CELERY_WORKER_MAX_MEMORY_PER_CHILD
                # Github Oauth
                # (for fetching information from GitHub from repos that have the Github App not installed.)
                - GITHUB_CLIENT_ID
                - GITHUB_CLIENT_SECRET
                # Github App Setup
                - GITHUB_APP_IDENTIFIER
                - GITHUB_APP_CLIENT_ID
                - GITHUB_APP_CLIENT_SECRET
                - GITHUB_AUTH_REDIRECT_URI
                - GITHUB_WEBHOOK_SECRET
                - GITHUB_PRIVATE_KEY
                # Codefrog
                - PROJECT_SOURCE_CODE_DIR
        ports:
            - "8000:8000"
        depends_on:
            - redis
        links:
            - redis
        env_file:
          - ./.env
        volumes:
            - project_source_code:/project_source_code

    celery_worker:
        image: codefroghq/codefrog:latest
        command: ["celery", "worker", "--app", "core", "--queues", "low,medium,high,celery", "--loglevel", "INFO", "--pidfile", "/tmp/celery-worker.pid"]
        restart: unless-stopped
        build:
            context: .
            args:
                # Django
                - DEBUG
                - SECRET_KEY
                - ALLOWED_HOSTS
                - STATIC_ROOT
                - LOG_LEVEL
                # Database
                - DATABASE_URL
                # Celery
                - CELERY_BROKER_URL
                - CELERY_TASK_ALWAYS_EAGER
                - CELERY_WORKER_MAX_TASKS_PER_CHILD
                - CELERY_WORKER_MAX_MEMORY_PER_CHILD
                # Github Oauth
                # (for fetching information from GitHub from repos that have the Github App not installed.)
                - GITHUB_CLIENT_ID
                - GITHUB_CLIENT_SECRET
                # Github App Setup
                - GITHUB_APP_IDENTIFIER
                - GITHUB_APP_CLIENT_ID
                - GITHUB_APP_CLIENT_SECRET
                - GITHUB_AUTH_REDIRECT_URI
                - GITHUB_WEBHOOK_SECRET
                - GITHUB_PRIVATE_KEY
                # Codefrog
                - PROJECT_SOURCE_CODE_DIR
        depends_on:
            - redis
        links:
            - redis
        environment:
            - C_FORCE_ROOT=true
        env_file:
          - ./.env
        volumes:
            - project_source_code:/project_source_code

    celery_beat:
        image: codefroghq/codefrog:latest
        command: ["celery", "beat", "--app", "core", "--loglevel", "INFO", "--pidfile", "/tmp/celery-beat.pid", "--schedule", "/tmp/celery-beat-schedule.db"]
        restart: unless-stopped
        build:
            context: .
            args:
                # Django
                - DEBUG
                - SECRET_KEY
                - ALLOWED_HOSTS
                - STATIC_ROOT
                - LOG_LEVEL
                # Database
                - DATABASE_URL
                # Celery
                - CELERY_BROKER_URL
                - CELERY_TASK_ALWAYS_EAGER
                - CELERY_WORKER_MAX_TASKS_PER_CHILD
                - CELERY_WORKER_MAX_MEMORY_PER_CHILD
                # Github Oauth
                # (for fetching information from GitHub from repos that have the Github App not installed.)
                - GITHUB_CLIENT_ID
                - GITHUB_CLIENT_SECRET
                # Github App Setup
                - GITHUB_APP_IDENTIFIER
                - GITHUB_APP_CLIENT_ID
                - GITHUB_APP_CLIENT_SECRET
                - GITHUB_AUTH_REDIRECT_URI
                - GITHUB_WEBHOOK_SECRET
                - GITHUB_PRIVATE_KEY
                # Codefrog
                - PROJECT_SOURCE_CODE_DIR
        depends_on:
            - redis
        links:
            - redis
        environment:
            - C_FORCE_ROOT=true
        env_file:
          - ./.env
        volumes:
            - project_source_code:/project_source_code

    redis:
        image: redis:5-buster
        command: ["redis-server", "--appendonly", "yes"]
        restart: unless-stopped
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    project_source_code:
