FROM python:3-slim

# Setting up environment
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

# Django configuration
ARG DEBUG
ENV DEBUG=$DEBUG

ARG SECRET_KEY
ENV SECRET_KEY=$SECRET_KEY

ARG ALLOWED_HOSTS
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS

ARG STATIC_ROOT
ENV STATIC_ROOT=$STATIC_ROOT

ARG LOG_LEVEL
ENV LOG_LEVEL=$LOG_LEVEL

# Database configuration
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Celery configuration
ARG CELERY_BROKER_URL
ENV CELERY_BROKER_URL=$CELERY_BROKER_URL

ARG CELERY_TASK_ALWAYS_EAGER
ENV CELERY_TASK_ALWAYS_EAGER=$CELERY_TASK_ALWAYS_EAGER

ARG CELERY_WORKER_MAX_TASKS_PER_CHILD
ENV CELERY_WORKER_MAX_TASKS_PER_CHILD=$CELERY_WORKER_MAX_TASKS_PER_CHILD

ARG CELERY_WORKER_MAX_MEMORY_PER_CHILD
ENV CELERY_WORKER_MAX_MEMORY_PER_CHILD=$CELERY_WORKER_MAX_MEMORY_PER_CHILD

# Github Oauth configuration
# (for fetching information from GitHub from repos that have the Github App not installed.)
ARG GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID

ARG GITHUB_CLIENT_SECRET
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET

# Github App onfiguration
ARG GITHUB_APP_IDENTIFIER
ENV GITHUB_APP_IDENTIFIER=$GITHUB_APP_IDENTIFIER

ARG GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID

ARG GITHUB_APP_CLIENT_SECRET
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET

ARG GITHUB_AUTH_REDIRECT_URI
ENV GITHUB_AUTH_REDIRECT_URI=$GITHUB_AUTH_REDIRECT_URI

ARG GITHUB_WEBHOOK_SECRET
ENV GITHUB_WEBHOOK_SECRET=$GITHUB_WEBHOOK_SECRET

ARG GITHUB_PRIVATE_KEY
ENV GITHUB_PRIVATE_KEY=$GITHUB_PRIVATE_KEY

# Codefrog configuration
ARG PROJECT_SOURCE_CODE_DIR
ENV PROJECT_SOURCE_CODE_DIR=$PROJECT_SOURCE_CODE_DIR

WORKDIR /app

# Install dependencies
RUN apt-get update -qy \
    && apt-get install -qy --no-install-recommends \
        git-core \
        libpq-dev \
        make \
        automake \
        gcc \
        g++ \
        subversion \
        python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Copy application code
COPY maintainer maintainer

# Silence warning about the missing .env file
RUN touch /app/.env

WORKDIR /app/maintainer/

RUN useradd --create-home --shell /bin/bash celery

CMD ["celery", "-A", "core", "worker", "-Q", "low,medium,high,celery", "--uid", "celery"]
