# Generated by Django 2.2 on 2019-04-20 12:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('git_reference', models.CharField(max_length=40, null=True)),
                ('complexity', models.IntegerField(null=True)),
                ('loc', models.IntegerField(null=True)),
                ('jira_bug_issues', models.IntegerField(null=True)),
                ('gitlab_bug_issues', models.IntegerField(null=True)),
                ('sentry_errors', models.IntegerField(null=True)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'unique_together': {('project_slug', 'date')},
            },
        ),
    ]
