# Generated by Django 2.1.3 on 2019-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('git_reference', models.CharField(max_length=30)),
                ('metric', models.IntegerField()),
            ],
        ),
    ]
