# Generated by Django 2.2 on 2019-04-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='gitlab_bug_issues',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='jira_bug_issues',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='sentry_errors',
        ),
    ]
