# Generated by Django 2.2 on 2019-04-26 08:32

from django.db import migrations


def up(apps, schema_editor):
    Project = apps.get_model('main', 'Project')

    Project.objects.create(
        name='Requests',
        slug='requests',
        source_dir='/projects/requests/requests',
        external_services={

        },
    )

    Project.objects.create(
        name='Flask',
        slug='flask',
        source_dir='/projects/flask/flask',
        external_services={

        },
    )

    Project.objects.create(
        name='Keras',
        slug='keras',
        source_dir='/projects/keras/keras',
        external_services={

        },
    )

    Project.objects.create(
        name='Formunauts Backend',
        slug='donut-backend',
        source_dir='/projects/backend/server/django-donut',
        external_services={
            'gitlab': {
                'personal_access_token': 'iqZyDH1t7BtjiQHsRssa',
                'group': 'die-gmbh',
                'project': 'donation',
            },
            'sentry': {
                'auth_token': 'a1f913abcb794e709b8ad8a82b1966e51d10df638b8c4fcc9fd165b25ddaa537',
                'organization_slug': 'formunauts-gmbh',
                'project_slug': 'backend-live',
            },
        },
    )

def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=down),
    ]
