# Generated by Django 2.1.3 on 2019-04-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190418_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='projet_slug',
            new_name='project_slug',
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('project_slug', 'date', 'git_reference')},
        ),
    ]
