# Generated by Django 2.1.3 on 2019-04-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190418_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='metric',
        ),
        migrations.AddField(
            model_name='metric',
            name='complexity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='metric',
            name='gitlab_bug_issues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='metric',
            name='jira_bug_issues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='metric',
            name='loc',
            field=models.IntegerField(default=-1),
        ),
    ]
