# Generated by Django 2.1.3 on 2019-04-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190419_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='sentry_errors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='complexity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gitlab_bug_issues',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='jira_bug_issues',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='loc',
            field=models.IntegerField(null=True),
        ),
    ]
