# Generated by Django 2.2 on 2020-05-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"ordering": ["-timestamp"]},
        ),
    ]
