# Generated by Django 2.2 on 2020-06-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sourcenode_sourcestatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sourcenode",
            unique_together={("parent", "name")},
        ),
    ]
