# Generated by Django 2.2 on 2020-06-16 07:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200615_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='source_tree_metrics',
        ),
        migrations.AddField(
            model_name='sourcestatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sourcenode',
            name='ownership',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
