# Generated by Django 2.2 on 2020-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200616_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_branch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
