# Generated by Django 2.2 on 2020-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_git_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.Project'),
        ),
    ]
