# Generated by Django 2.2 on 2020-01-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
