# Generated by Django 2.2 on 2020-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_source_tree_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newly_registered',
            field=models.BooleanField(default=True),
        ),
    ]
