# Generated by Django 2.2 on 2020-02-10 13:26

from django.db import migrations


def up(apps, schema_editor):
    Plan = apps.get_model('web', 'Plan')
    Plan.objects.create(
        name='Free',
        slug='free',
    )
    Plan.objects.create(
        name='Individual',
        slug='individual',
    )
    Plan.objects.create(
        name='Team',
        slug='team',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200210_1323'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop),
    ]
