# Generated by Django 2.2 on 2020-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200210_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_trial_period',
            field=models.BooleanField(default=False),
        ),
    ]
