# Generated by Django 2.2 on 2020-02-10 14:22

from django.db import migrations


def up(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    Plan.objects.filter(name='Free').update(has_trial_period=False, free_trial_days=0)
    Plan.objects.filter(name='Individual').update(has_trial_period=True, free_trial_days=14)
    Plan.objects.filter(name='Team').update(has_trial_period=True, free_trial_days=14)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200210_1422'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop),
    ]
