# Generated by Django 2.2 on 2019-09-03 13:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190531_1435'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField()),
                ('issue_refid', models.CharField(max_length=100)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'unique_together': {('project', 'issue_refid')},
            },
        ),
    ]
