# Generated by Django 2.2 on 2019-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191014_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_app_installation_refid',
            field=models.IntegerField(null=True),
        ),
    ]
