# Generated by Django 2.2 on 2019-12-10 14:19

from django.db import migrations


def up(apps, schema_editor):
    project_slugs = [
        'elasticsearch',
        'kubernetes',
        'vscode',
    ]
    Project = apps.get_model('core', 'Project')
    Project.objects.filter(slug=project_slugs).delete()

def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191210_1048'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=down),
    ]
