# Generated by Django 2.2 on 2020-01-14 08:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200114_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_tree_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
