# Generated by Django 2.2 on 2020-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_newly_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fastspring_account_refid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fastspring_subscription_refid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
