# Generated by Django 2.2 on 2019-10-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_openissue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openissue',
            unique_together=set(),
        ),
    ]
