# Generated by Django 2.2 on 2020-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechange",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
