# Generated by Django 2.2 on 2020-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_pullrequest_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechange",
            name="issue",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="engine.Issue",
            ),
        ),
    ]
