# Generated by Django 2.2 on 2020-10-13 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_auto_20201013_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
