# Generated by Django 2.2 on 2020-02-11 20:52

from django.db import migrations
from django.db.utils import IntegrityError


def up(apps, schema_editor):
    Plan = apps.get_model("web", "Plan")

    try:
        plan = Plan.objects.get(slug="free")
    except Plan.DoesNotExist:
        plan = None

    if not plan:
        Plan.objects.create(
            name="Free",
            slug="free",
            has_trial_period=False,
            free_trial_days=0,
        )

    try:
        plan = Plan.objects.get(slug="individual")
    except Plan.DoesNotExist:
        plan = None

    if not plan:
        Plan.objects.create(
            name="Individual",
            slug="individual",
            has_trial_period=True,
            free_trial_days=14,
        )

    try:
        plan = Plan.objects.get(slug="team")
    except Plan.DoesNotExist:
        plan = None

    if not plan:
        Plan.objects.create(
            name="Team",
            slug="team",
            has_trial_period=True,
            free_trial_days=14,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop),
    ]
