# Generated by Django 2.2 on 2020-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="handled",
            field=models.BooleanField(default=False),
        ),
    ]
