# Generated by Django 2.2 on 2020-08-31 15:23

from django.db import migrations


def up(apps, schema_editor):
    Plan = apps.get_model("web", "Plan")

    try:
        plan = Plan.objects.get(slug="minimum")
    except Plan.DoesNotExist:
        plan = None

    if not plan:
        Plan.objects.create(
            name="Minimum",
            slug="minimum",
            has_trial_period=True,
            free_trial_days=30,
        )

    # Update trial period for other plans
    Plan.objects.filter(free_trial_days=14).update(free_trial_days=30)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_message_handled"),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop),
    ]
