name: Create Sentry release

on:
  push:
    branches:
      - master
      - "release/*"

jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_LOG_LEVEL: debug
          SENTRY_URL: https://antonpirker.eu.ngrok.io/
        with:
          environment: production
          ignore_empty: True
          ignore_missing: True
          finalize: True
