name: Build - Test - Publish

on:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build container
      uses: antonpirker/Publish-Docker-Github-Action@master
      with:
        name: codefroghq/codefrog
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        push: false

#    TODO: fix the problem, that I need a Postgres Database to run the tests and then reactivate.
#    - name: Run tests in container
#      run: |
#        docker run \
#          --env "SECRET_KEY=not_so_important_during_testing" \
#          --env "DATABASE_URL=sqlite:////tmp/my-tmp-sqlite.db" \
#          codefroghq/codefrog \
#          ./manage.py test

    - name: Publish container to DockerHub
      uses: antonpirker/Publish-Docker-Github-Action@master
      with:
        name: codefroghq/codefrog
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        build: false

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    # TODO: Add the actual "deployment to production" functionality
    - name: Deploy to production
      if: github.ref == 'refs/heads/master'
      run: |
        rm -rf /tmp/.ssh/
        mkdir -p /tmp/.ssh/
        echo "${{ secrets.DEPLOY_KEY_PRODUCTION }}" > /tmp/.ssh/id_rsa
        chmod 700 /tmp/.ssh/ -R
        chmod 600 /tmp/.ssh/id_rsa
        scp -v -i /tmp/.ssh/id_rsa ./docker-compose.yml codefrog@142.93.196.203:/codefrog/
