name: Publish

on:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build container
      uses: antonpirker/Publish-Docker-Github-Action@master
      with:
        name: codefroghq/codefrog
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        push: false

    - name: Run tests in container
      run: |
        docker ps -a

#    - name: Publish container to DockerHub
#      uses: antonpirker/Publish-Docker-Github-Action@master
#      with:
#        name: codefroghq/codefrog
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        build: false
